### ISSUE TITLE
Hardware list for meteorological station (RACIMO)

### ISSUE THREAD

**Issue by camachoreina** [LA-CoNGA/WP5-Dissemination#5]
To be updated!

**Comment by DennisCazar** [comment]
En este espacio revisaremos el diseño de la estación RACIMO y la actualizaremos para implementarla dentro de LA-CoNGA.
Podríamos dividir el trabajo en 2 frentes HW y SW.
Tengo ya dos estudiantes de ingeniería que me darán una mano.
¿Luis podrías subir el material?

**Comment by nunezluis** [comment]
La lista de los componentes está disponible en https://circuitmaker.com/Projects/Details/Karen-Forero/Racimo-AireV1 

Además añadí un directorio en WP5 con toda la info de RACIMO
