### ISSUE TITLE
Ajuste del objetivo

### ISSUE THREAD

**Issue by jedsrz** [LA-CoNGA/WP5-Dissemination#9]
Por razones de rr.pp y otras en http://laconga.redclara.net/ y http://laconga.redclara.net/about/ donde dice

The ​primary objective of the Latin-american Alliance for Capacity buildiNG in Advanced Physics (LA-CoNGA Physics) proposal is to *modernize* the educational platform in eight Latin-American higher education institutions (HEI) from four countries ...

colocar

The ​primary objective of the Latin-american Alliance for Capacity buildiNG in Advanced Physics (LA-CoNGA Physics) proposal is to *collaborate in the modernization* of the educational platform in eight Latin-American higher education institutions (HEI) from four countries...

**Comment by jedsrz** [comment]
Por razones de rr.pp y otras en http://laconga.redclara.net/ y http://laconga.redclara.net/about/ donde dice

The ​primary objective of the Latin-american Alliance for Capacity buildiNG in Advanced Physics (LA-CoNGA Physics) proposal is to *modernize* the educational platform in eight Latin-American higher education institutions (HEI) from four countries ...

colocar

The ​primary objective of the Latin-american Alliance for Capacity buildiNG in Advanced Physics (LA-CoNGA Physics) proposal is to *collaborate in the modernization* of the educational platform in eight Latin-American higher education institutions (HEI) from four countries...

**Comment by ocariz** [comment]
Buen punto, @jedsrz. Ya corregimos las fuentes html relevantes.
